import assert from "node:assert/strict";
import {parseHTML} from "linkedom";
const {window}=parseHTML("<!doctype html><html><body></body></html>");
for(const key of ["document","customElements","HTMLElement","Node","Event","CustomEvent","MutationObserver","Element","ShadowRoot","HTMLInputElement","HTMLSelectElement"])if(window[key])globalThis[key]=window[key];
globalThis.window=window;
globalThis.requestAnimationFrame=callback=>setTimeout(callback,0);
globalThis.cancelAnimationFrame=clearTimeout;
globalThis.ResizeObserver=class{observe(){} disconnect(){}};
globalThis.CSS={escape:String};
// Linkedom exposes select.value as getter-only; browsers provide this setter.
const selectValue=Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype,"value");
Object.defineProperty(window.HTMLSelectElement.prototype,"value",{configurable:true,get:selectValue.get,set(value){for(const option of this.options)option.selected=option.value===String(value);}});
const storage=new Map();
globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};

// Reproduce a session with an already registered old panel constructor.
await import("../custom_components/cook4me/frontend/cook4me-panel-v61.js");
const OldPanel=customElements.get("cook4me-recipe-hub-panel-v61");
OldPanel.prototype._ingredientNutritionHtml=()=>"LEGACY NUTRIENT POPUP";
await import("../custom_components/cook4me/frontend/cook4me-panel-v62-bundle.js");
const Panel=customElements.get("cook4me-recipe-hub-panel-v62");
assert.notEqual(Object.getPrototypeOf(Panel),OldPanel,"The new bundle must not inherit a cached old constructor");
const panel=document.createElement("cook4me-recipe-hub-panel-v62");
panel._entryId="entry";
panel._entries=[{entry_id:"entry",title:"Cook4Me",profile:{houseIngredients:[]},recipes:[]}];
const rice={ingredientId:"M_FOOD_421",foodKey:"M_FOOD_421",foodName:"Arroz"};
const requests=[];
const choices=[{ingredientId:"M_FOOD_421",id:"M_FOOD_421",key:"M_FOOD_421",name:"Ρύζι",foodName:"Ρύζι",displayLanguage:"el",presentationVersion:62,sourceIngredientIds:["M_FOOD_421"]}];
const info={ingredientInfoContract:"offline-ingredient-info-v62",ingredient:{name:"Ρύζι"},stock:null,catalogNutrition:null,genericNutrition:null,exactNutritionLots:[],nutritionReferences:[{name:"Μαγειρεμένο ρύζι",referenceOnly:true,nutrition:{basisQuantity:100,basisUnit:"g",values:{energyKcal:129,protein:2.7,fat:null}}}],officialRecipeUsage:[{title:"Ρύζι",displayFamilyId:"family:rice",searchVariantId:"278301"}]};
panel._hass={language:"el",user:{id:"test"},states:{},connection:{sendMessagePromise:async msg=>{requests.push(msg);return msg.type.endsWith("ingredient_catalog")?{items:choices,language:"el",presentationVersion:62}:info;}}};
panel._capabilities={languages:[{code:"de"},{code:"pt"}],deviceCatalogLanguage:"de"};
panel._renderShell();
panel._cook4meApiTail=new Promise(()=>{});
await panel._showIngredientInfo(rice,{ingredients:[rice]});
assert.equal(requests.at(-1).type,"cook4me/v31/ingredient_info");
assert.equal(requests.at(-1).language,"el");
const dialog=panel.shadowRoot.querySelector("[data-ingredient-dialog]");
assert.ok(dialog);
assert.ok(dialog.textContent.includes("Ρύζι"));
assert.ok(dialog.textContent.includes("Μαγειρεμένο ρύζι"));
assert.ok(dialog.textContent.includes("129 kcal"));
assert.ok(dialog.textContent.includes("ανά 100 g"));
assert.ok(dialog.querySelector("[data-reference-only]"));
assert.equal(dialog.querySelector('[data-nutrient="fat"]'),null);
assert.equal(dialog.querySelectorAll("[data-use]").length,1,"Repeated publications should be one related recipe");
assert.ok(!dialog.textContent.includes("LEGACY NUTRIENT POPUP"));
dialog.querySelector("[data-close]").click();
assert.equal(panel.shadowRoot.querySelector("[data-ingredient-dialog]"),null);

const translated={ingredients:[{...rice}],sourceLanguage:"pt"};
panel._applyTranslation(translated,{ingredients:["Ρύζι"]});
await panel._showIngredientInfo("Ρύζι",translated);
assert.equal(requests.at(-1).ingredient.ingredientId,"M_FOOD_421");
panel.shadowRoot.querySelector("[data-close]").click();

panel._ingredientCatalog=[{name:"/2 onion, peeled and chopped"}];
panel._discardOldCatalog();assert.deepEqual(panel._ingredientCatalog,[]);
const originalRender=panel._renderTab.bind(panel);
panel._renderTab=()=>{};
await panel._loadIngredientCatalog("pt");
assert.equal(requests.at(-1).language,"el","Ingredient choices follow UI language, independently of source catalog");
assert.equal(panel._ingredientCatalog[0].name,"Ρύζι");
assert.ok(panel._resourceHasData("catalog"));
const sendMessage=panel._hass.connection.sendMessagePromise;
panel._message=()=>{};
let failedRequests=0;
panel._hass.connection.sendMessagePromise=async()=>{failedRequests++;throw new Error("unavailable");};
await panel._loadIngredientCatalog(null,true);
await panel._loadIngredientCatalog();
assert.equal(failedRequests,1,"Rendering after a failed fetch must not loop requests");
panel._hass.connection.sendMessagePromise=sendMessage;
await panel._loadIngredientCatalog(null,true);
assert.equal(panel._v62CatalogFailureKey,null,"Explicit retry clears the error latch");
panel._hass.language="de";panel._discardOldCatalog();assert.deepEqual(panel._ingredientCatalog,[]);
assert.equal(panel._resourceHasData("catalog"),false,"Changing UI language invalidates the old locale");
panel._hass.language="el";
panel._ingredientCatalog=choices;
panel._houseIngredients=[];panel._houseEntryId="entry";panel._inventoryLoadedEntry="entry";
panel._tab="profile";panel._renderTab=originalRender;
panel._renderTab();
assert.equal(panel.shadowRoot.querySelector("#ingredientLanguage"),null,"Ingredient source-language selector should not appear");
assert.ok(panel.shadowRoot.querySelector("#houseCatalog")?.textContent.includes("Ρύζι"));
panel._houseFilter="ρυζι";
panel._renderHouseChoices(panel.shadowRoot);
assert.ok(panel.shadowRoot.querySelector("#houseCatalog")?.textContent.includes("Ρύζι"),"Greek search accepts omitted accents");
assert.equal(panel.getAttribute("data-cook4me-build"),"2026.9.15.4");
assert.equal(panel._recipeKey({displayFamilyId:"family:rice",groupingFunctionalId:"variant-group"}),"family:rice");
await panel._api("cook4me/v7/recipe_detail",{variant_id:"258313"});
assert.equal(requests.at(-1).type,"cook4me/v31/recipe_detail","Quantity/language selection must use offline detail routing");
panel.disconnectedCallback();
console.log("v62 deployed bundle, stale constructor isolation, rice references, ingredient names and offline variant routing OK");
