import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
const {window}=parseHTML('<!doctype html><html><body></body></html>');
for(const key of ['document','customElements','HTMLElement','Node','Event','CustomEvent','MutationObserver','Element','ShadowRoot','HTMLInputElement','HTMLSelectElement'])if(window[key])globalThis[key]=window[key];
globalThis.window=window;globalThis.requestAnimationFrame=callback=>setTimeout(callback,0);globalThis.cancelAnimationFrame=clearTimeout;
globalThis.ResizeObserver=class{observe(){} disconnect(){}};globalThis.CSS={escape:String};
const selectValue=Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype,'value');
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get:selectValue.get,set(value){for(const option of this.options)option.selected=option.value===String(value);}});
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};
await import('../custom_components/cook4me/frontend/cook4me-panel-v72-bundle.js');
const panel=document.createElement('cook4me-recipe-hub-panel-v72');
const tick=()=>new Promise(resolve=>setTimeout(resolve,15));
const requests=[],subscriptions=[];let unsubscriptions=0;
const defaults={enabled:false,recipe:true,steps:true,state:true,connection:false,players:[],tts:'',ai:'',language:'',voice:''};
const choices={players:[{id:'media_player.kitchen',name:'Kitchen',announce:true},{id:'media_player.living',name:'Living room',announce:false}],
 tts:[{id:'tts.piper',name:'Piper',languages:['en_US','el_GR'],defaultLanguage:'en_US',voices:{el_GR:[{id:'greek',name:'Greek voice'}]}}],ai:[{id:'ai_task.local',name:'Local AI Task'}]};
const saved=new Map();let delay=null;
const connection={subscribeMessage:async (callback,message)=>{subscriptions.push({callback,message});return()=>unsubscriptions++;}};
panel._hass={language:'el',user:{id:'alice'},config:{country:'DE'},states:{},connection};
panel._entryId='one';panel._entries=[{entry_id:'one',title:'Kitchen Cook4Me',connected:true,state:{phase:'idle',uiFirmware:'3.7.3',wifiFirmware:'3.3.2'},recipes:[],profile:{}},{entry_id:'two',title:'Other Cook4Me',state:{},recipes:[],profile:{}}];
panel._renderTab=()=>{};panel._loadOverview=async()=>{};panel._loadBookState=async()=>{};
panel._api=async(type,data)=>{
 requests.push({type,...data});
 if(type.endsWith('device_settings')){
  const key=panel._hass.user.id+data.entry_id;
  if(data.settings)saved.set(key,structuredClone(data.settings));
  if(delay)await delay;
  return {settings:structuredClone(saved.get(key)||defaults),choices:structuredClone(choices)};
 }
 return {done:true};
};
panel._renderShell();panel._updateHeader();await tick();
const dialog=()=>panel.shadowRoot.querySelector('[data-device-settings]');
panel.shadowRoot.querySelector('#status .status').click();await tick();
assert.ok(dialog(),'Device header opens settings');assert.match(dialog().textContent,/Ανακοινώσεις/);
const change=(selector,value)=>{const el=dialog().querySelector(selector);if(el.type==='checkbox')el.checked=value;else el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));};
change('[data-setting=enabled]',true);change('[data-setting=tts]','tts.piper');
assert.equal(panel._v72Draft.language,'el_GR','TTS language defaults to UI language when supported');
change('[data-setting=voice]','greek');change('[data-setting=ai]','ai_task.local');
change('[data-player="media_player.kitchen"]',true);change('[data-player="media_player.living"]',true);
assert.equal(dialog().querySelector('[data-v72-count]').textContent,'2');
await panel._v72SaveSettings(false);
assert.deepEqual(saved.get('aliceone').players,['media_player.kitchen','media_player.living']);assert.equal(saved.get('aliceone').voice,'greek');
assert.ok(!requests.some(r=>'user_id' in r),'User identity is server-derived');
await panel._v72SaveSettings(true);assert.ok(requests.some(r=>r.type.endsWith('announcement_test')));
panel._v72CloseSettings();await panel._v72OpenSettings();assert.equal(panel._v72Draft.ai,'ai_task.local');
panel._hass={...panel._hass,user:{id:'bob'}};panel._updateHeader();await tick();assert.equal(dialog(),null,'User switch closes private settings');
await panel._v72OpenSettings();assert.equal(panel._v72Draft.enabled,false,'Other user has independent defaults');
panel._entryId='two';panel._updateHeader();await tick();assert.equal(dialog(),null);await panel._v72OpenSettings();assert.equal(panel._v72Draft.players.length,0);
assert.ok(unsubscriptions>=2,'Subscriptions are renewed for user and device changes');
panel._v72CloseSettings();await new Promise(resolve=>setTimeout(resolve,800));
subscriptions.at(-1).callback({state:'translating'});
assert.equal(panel.shadowRoot.querySelectorAll('.rx-v59-op').length,1,'Announcements use existing bottom-right popup');
assert.match(panel.shadowRoot.querySelector('.rx-v59-op').textContent,/Μετάφραση ανακοίνωσης/);
subscriptions.at(-1).callback({state:'error',detail:'AI unavailable'});
assert.match(panel.shadowRoot.querySelector('.rx-v59-op').textContent,/AI unavailable/);
let release;delay=new Promise(resolve=>release=resolve);const pending=panel._v72OpenSettings();
panel._hass={...panel._hass,user:{id:'alice'}};panel._updateHeader();release();await pending;delay=null;
assert.equal(dialog(),null,'Late settings response from previous user is discarded');
globalThis.location={search:'?device=one'};panel._updateHeader();await tick();assert.equal(panel._entryId,'one');assert.ok(dialog(),'HA device link opens the right settings');
globalThis.location={search:''};panel.disconnectedCallback();await tick();assert.equal(dialog(),null);
console.log('v72 device settings, per-user/device selections, supported TTS languages/voices, multi-speaker controls, test action and private progress passed');
