import assert from "node:assert/strict";
import {parseHTML} from "linkedom";

const {window}=parseHTML("<!doctype html><html><body></body></html>");
for(const key of ["document","customElements","HTMLElement","Node","Event","CustomEvent","MutationObserver","Element","ShadowRoot","HTMLInputElement","HTMLSelectElement"])if(window[key])globalThis[key]=window[key];
globalThis.window=window;
globalThis.requestAnimationFrame=callback=>setTimeout(callback,0);
globalThis.cancelAnimationFrame=clearTimeout;
globalThis.ResizeObserver=class{observe(){} disconnect(){}};
globalThis.CSS={escape:String};
const storage=new Map();
globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};
await import("../custom_components/cook4me/frontend/cook4me-panel-v61.js");

const panel=document.createElement("cook4me-recipe-hub-panel-v61");
panel._hass={language:"el",user:{id:"test"},states:{},connection:{sendMessagePromise:async()=>({items:[]})}};
panel._entryId="entry";
panel._entries=[{entry_id:"entry",title:"Cook4Me",connected:false}];
panel._capabilities={languages:[{code:"de"},{code:"fr"},{code:"it"}],deviceCatalogLanguage:"de"};
panel._catalogLanguage="auto";
assert.deepEqual(panel._loadOfficialLanguages(),["de","fr","it"],"New search should include all source catalogs");
panel._saveOfficialLanguages(["de-DE"]);
assert.deepEqual(panel._loadOfficialLanguages(),["de"],"Explicit selection must survive normalization");
panel._saveOfficialLanguages(["el"]);
assert.deepEqual(panel._loadOfficialLanguages(),["de","fr","it"],"Stale unsupported source language must not hide the catalog");
panel._saveOfficialLanguages([]);
assert.deepEqual(panel._loadOfficialLanguages(),[],"Deselect all must not secretly select a fallback");
panel._entryId="other";
panel._capabilities={};
assert.equal(panel._loadOfficialLanguages().length,21,"Audited source languages must remain available while options load");
panel._capabilities={languages:[{code:"de"},{code:"it"}]};
assert.deepEqual(panel._loadOfficialLanguages(),["de","it"]);
panel._saveOfficialLanguages(["de"]);

panel._renderShell();
const content=panel.shadowRoot.querySelector("#content");
panel._renderOfficial(content);
const picker=content.querySelector("#officialCatalogLanguages");
assert.ok(picker,"Catalog picker must render");
assert.ok(picker.querySelector("[data-close-catalog]"),"Mobile picker needs an explicit close control");
picker.setAttribute("open","");
panel._v60OutsidePointer({composedPath:()=>[picker.querySelector("input"),picker]});
assert.ok(picker.hasAttribute("open"),"Picking a language must keep the picker open");
panel._v60OutsidePointer({composedPath:()=>[content]});
assert.ok(!picker.hasAttribute("open"),"Outside pointer must close the picker");
picker.setAttribute("open","");
picker.querySelector("[data-close-catalog]").click();
assert.ok(!picker.hasAttribute("open"));
panel.disconnectedCallback();
const hass=panel._hass;panel._hass=null;panel.connectedCallback();panel._hass=hass;
picker.setAttribute("open","");
const escape=new Event("keydown");Object.defineProperty(escape,"key",{value:"Escape"});document.dispatchEvent(escape);
assert.ok(!picker.hasAttribute("open"),"Escape handler must be restored after reconnect");

const missing={catalogNutrition:{perServing:{},totals:{energyKcal:null},coverage:0}};
assert.equal(panel._v60Nutrition(missing),null,"Missing nutrition is not zero nutrition");
const partial={title:"Test",searchVariantId:"test",language:"de",ingredients:[],steps:[],match:{safe:true},catalogNutrition:{perServing:{},totals:{energyKcal:100,protein:0,fat:null,fiber:""},coverage:0.5,estimated:true}};
let data=panel._v60Nutrition(partial);
assert.equal(data.energy,100);assert.equal(data.protein,0);assert.equal(data.fat,null);assert.equal(data.fiber,null);assert.equal(data.perServing,false);
assert.equal(panel._v60Nutrition({nutrition:{totals:{energyKcal:50}}}).coverage,null);
assert.equal(panel._v60Nutrition({catalogNutrition:{perServing:{}},nutrition:{perServing:{energyKcal:40}}}).energy,40);
const card=panel._recipeCard(partial);
assert.equal((card.match(/100 kcal/g)||[]).length,1,"Nutrition values should appear once");
assert.ok(card.includes(panel._t("recipeTotal")));assert.ok(card.includes(panel._t("partialNutrition")));
const perServing=panel._v60Nutrition({...partial,catalogNutrition:{perServing:{energyKcal:25},totals:{energyKcal:100}}});
assert.equal(perServing.energy,25);assert.equal(perServing.perServing,true);

const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
const requests=[];const translation=deferred();
panel._hass.connection.sendMessagePromise=msg=>{const request=deferred();requests.push({msg,...request});return request.promise;};
panel._shouldTranslate=()=>true;panel._translationNeeded=()=>true;
panel._translateItems=()=>translation.promise;
panel._tab="official";
let renders=0;panel._renderTab=()=>{renders++;};
// A pending cloud operation must not delay an immutable catalog read.
panel._cook4meApiTail=new Promise(()=>{});
const first=panel._search("ριζότο");
assert.equal(requests.length,1);assert.equal(requests[0].msg.query_language,"el");assert.deepEqual(requests[0].msg.languages,["de"]);
requests[0].resolve({items:[{...partial,title:"First"}]});
await first;
assert.equal(panel._results[0].title,"First","Local results must appear while translation is still pending");
assert.ok(renders>0);
const old=panel._search("old"),latest=panel._search("latest");
requests[2].resolve({items:[{...partial,title:"Latest"}]});await latest;
requests[1].resolve({items:[{...partial,title:"Old"}]});await old;
assert.equal(panel._results[0].title,"Latest","An older search must not overwrite newer results");
translation.resolve();await Promise.resolve();
panel._saveOfficialLanguages([]);
const count=requests.length;await panel._search("risotto");
assert.equal(requests.length,count,"Explicitly deselected catalogs must not trigger an all-catalog search");
panel.disconnectedCallback();
console.log("v61 offline search, source languages, reconnect, nutrition, and stale response regressions OK");
