#!/usr/bin/env python3
"""Build Recipe Hub v116 from the immutable v115 bundle plus the v116 layer."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v115-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v116.js"
TARGET = FRONTEND / "cook4me-panel-v116-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v115\.js["\'];\s*$', re.M)


def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v115.py; edit the source layers.",
        "// Generated by tools/build_frontend_bundle_v116.py from immutable v115 bundle plus v116 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v115";',
        'const activeElement="cook4me-recipe-hub-panel-v116";',
        1,
    )
    base = base.replace("-build-2026091719", "-build-202609182", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v116.js\n(() => {\n" + source + "\n})();\n"


if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v116 bundle needs regeneration: python tools/build_frontend_bundle_v116.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v116 frontend bundle is current")
