#!/usr/bin/env python3
"""Build Recipe Hub v123 from the immutable v122 bundle plus verified torch support."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v122-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v123.js"
TARGET = FRONTEND / "cook4me-panel-v123-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v122\.js["\'];\s*$', re.M)

def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v122.py from immutable v121 bundle plus v122 source.",
        "// Generated by tools/build_frontend_bundle_v123.py from immutable v122 bundle plus v123 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v122";',
        'const activeElement="cook4me-recipe-hub-panel-v123";',
        1,
    )
    base = base.replace("-build-202609191", "-build-202609192", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v123.js\n(() => {\n" + source + "\n})();\n"

if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v123 bundle needs regeneration: python tools/build_frontend_bundle_v123.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v123 frontend bundle is current")
