#!/usr/bin/env python3
"""Build Recipe Hub v121 from the immutable v120 bundle plus the v121 mobile scanner layer."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v120-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v121.js"
TARGET = FRONTEND / "cook4me-panel-v121-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v120\.js["\'];\s*$', re.M)

def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v120.py from immutable v119 bundle plus v120 source.",
        "// Generated by tools/build_frontend_bundle_v121.py from immutable v120 bundle plus v121 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v120";',
        'const activeElement="cook4me-recipe-hub-panel-v121";',
        1,
    )
    base = base.replace("-build-202609186", "-build-202609187", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v121.js\n(() => {\n" + source + "\n})();\n"

if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v121 bundle needs regeneration: python tools/build_frontend_bundle_v121.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v121 frontend bundle is current")
