#!/usr/bin/env python3
"""Build Recipe Hub v126 from the immutable v125 bundle plus uniform menu footers."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v125-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v126.js"
TARGET = FRONTEND / "cook4me-panel-v126-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v125\.js["\'];\s*$', re.M)

def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v125.py from immutable v124 bundle plus v125 source.",
        "// Generated by tools/build_frontend_bundle_v126.py from immutable v125 bundle plus v126 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v125";',
        'const activeElement="cook4me-recipe-hub-panel-v126";',
        1,
    )
    base = base.replace("-build-202609194", "-build-202609195", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v126.js\n(() => {\n" + source + "\n})();\n"

if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v126 bundle needs regeneration: python tools/build_frontend_bundle_v126.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v126 frontend bundle is current")
