#!/usr/bin/env python3
"""Build Recipe Hub v125 from the immutable v124 bundle plus flush filter footer layout."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v124-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v125.js"
TARGET = FRONTEND / "cook4me-panel-v125-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v124\.js["\'];\s*$', re.M)

def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v124.py from immutable v123 bundle plus v124 source.",
        "// Generated by tools/build_frontend_bundle_v125.py from immutable v124 bundle plus v125 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v124";',
        'const activeElement="cook4me-recipe-hub-panel-v125";',
        1,
    )
    base = base.replace("-build-202609193", "-build-202609194", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v125.js\n(() => {\n" + source + "\n})();\n"

if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v125 bundle needs regeneration: python tools/build_frontend_bundle_v125.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v125 frontend bundle is current")
