#!/usr/bin/env python3
"""Build Recipe Hub v118 from the immutable v117 bundle plus the v118 UI layer."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v117-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v118.js"
TARGET = FRONTEND / "cook4me-panel-v118-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v117\.js["\'];\s*$', re.M)


def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v117.py from immutable v116 bundle plus v117 source.",
        "// Generated by tools/build_frontend_bundle_v118.py from immutable v117 bundle plus v118 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v117";',
        'const activeElement="cook4me-recipe-hub-panel-v118";',
        1,
    )
    base = base.replace("-build-202609183", "-build-202609184", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v118.js\n(() => {\n" + source + "\n})();\n"


if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v118 bundle needs regeneration: python tools/build_frontend_bundle_v118.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v118 frontend bundle is current")
