#!/usr/bin/env python3
"""Build Recipe Hub v126 from the immutable v125 bundle plus selected source overlays."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v125-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v126.js"
TARGET = FRONTEND / "cook4me-panel-v126-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v125\.js["\'];\s*$', re.M)
PANEL_IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v\d+\.js["\'];\s*$', re.M)
SOURCE_OVERLAYS = (23, 43, 49, 93, 117)


def _overlay_panel(base: str, version: int) -> str:
    """Replace one embedded legacy panel with its current standalone source."""
    marker = f"// cook4me-panel-v{version}.js\n"
    next_marker = f"// cook4me-panel-v{version + 1}.js\n"
    start = base.index(marker)
    end = base.index(next_marker, start)
    source_path = FRONTEND / f"cook4me-panel-v{version}.js"
    source = PANEL_IMPORT.sub("", source_path.read_text(encoding="utf-8"), count=1).strip()
    replacement = marker + "(() => {\n\n" + source + "\n\n})();\n"
    return base[:start] + replacement + base[end:]


def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    for version in SOURCE_OVERLAYS:
        base = _overlay_panel(base, version)
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v125.py from immutable v124 bundle plus v125 source.",
        "// Generated by tools/build_frontend_bundle_v126.py from immutable v125 bundle plus selected source overlays and v126 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v125";',
        'const activeElement="cook4me-recipe-hub-panel-v126";',
        1,
    )
    base = base.replace("-build-202609194", "-build-202609195", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v126.js\n(() => {\n" + source + "\n})();\n"


if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v126 bundle needs regeneration: python tools/build_frontend_bundle_v126.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v126 frontend bundle is current")
