#!/usr/bin/env python3
"""Build Recipe Hub v120 from the immutable v119 bundle plus the v120 camera layer."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v119-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v120.js"
TARGET = FRONTEND / "cook4me-panel-v120-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v119\.js["\'];\s*$', re.M)


def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v119.py from immutable v118 bundle plus v119 source.",
        "// Generated by tools/build_frontend_bundle_v120.py from immutable v119 bundle plus v120 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v119";',
        'const activeElement="cook4me-recipe-hub-panel-v120";',
        1,
    )
    base = base.replace("-build-202609185", "-build-202609186", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v120.js\n(() => {\n" + source + "\n})();\n"


if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v120 bundle needs regeneration: python tools/build_frontend_bundle_v120.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v120 frontend bundle is current")
