#!/usr/bin/env python3
"""Bundle the existing panel layers under a fresh custom-element registry scope."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
TARGET = FRONTEND / "cook4me-panel-v87-bundle.js"
IMPORT = re.compile(r'^import ["\']\./(cook4me-panel-v\d+\.js)["\'];\s*$', re.M)


def bundle():
    seen, bodies = set(), []
    def visit(name):
        if name in seen:
            return
        seen.add(name)
        source = (FRONTEND/name).read_text()
        for dependency in IMPORT.findall(source):
            visit(dependency)
        source = IMPORT.sub("", source)
        bodies.append(f"// {name}\n(() => {{\n{source}\n}})();\n")
    visit("cook4me-panel-v87.js")
    # Previously loaded panel constructors cannot replace the new layer chain.
    return """// Generated by tools/build_frontend_bundle_v87.py; edit the source layers.
const activeElement="cook4me-recipe-hub-panel-v87";
const scope=name=>name===activeElement?name:`${name}-build-2026091611`;
const customElements={get:name=>globalThis.customElements.get(scope(name)),define:(name,ctor)=>globalThis.customElements.define(scope(name),ctor)};
"""+"\n".join(bodies)


if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != value:
            raise SystemExit("The v87 bundle needs regeneration: python tools/build_frontend_bundle_v87.py")
    else:
        TARGET.write_text(value)
    print("v87 frontend bundle is current")
