#!/usr/bin/env python3
"""Build Recipe Hub v122 from the immutable v121 bundle plus the v122 torch fallback layer."""
from pathlib import Path
import re
import sys

FRONTEND = Path(__file__).resolve().parents[1] / "custom_components/cook4me/frontend"
BASE = FRONTEND / "cook4me-panel-v121-bundle.js"
SOURCE = FRONTEND / "cook4me-panel-v122.js"
TARGET = FRONTEND / "cook4me-panel-v122-bundle.js"
IMPORT = re.compile(r'^import ["\']\./cook4me-panel-v121\.js["\'];\s*$', re.M)

def bundle() -> str:
    base = BASE.read_text(encoding="utf-8")
    base = base.replace(
        "// Generated by tools/build_frontend_bundle_v121.py from immutable v120 bundle plus v121 source.",
        "// Generated by tools/build_frontend_bundle_v122.py from immutable v121 bundle plus v122 source.",
        1,
    )
    base = base.replace(
        'const activeElement="cook4me-recipe-hub-panel-v121";',
        'const activeElement="cook4me-recipe-hub-panel-v122";',
        1,
    )
    base = base.replace("-build-202609187", "-build-202609191", 1)
    source = IMPORT.sub("", SOURCE.read_text(encoding="utf-8"), count=1)
    return base.rstrip() + "\n// cook4me-panel-v122.js\n(() => {\n" + source + "\n})();\n"

if __name__ == "__main__":
    value = bundle()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != value:
            raise SystemExit(
                "The v122 bundle needs regeneration: python tools/build_frontend_bundle_v122.py"
            )
    else:
        TARGET.write_text(value, encoding="utf-8")
    print("v122 frontend bundle is current")
