#!/usr/bin/env python3
from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'tests/test_compile_release_catalog_semantics_v60.py'
text = path.read_text(encoding='utf-8')
old = '''        confirmed = mod.compile_from_paths(paths)\n        total = len(confirmation_items) + len(syntax_ids)\n\n        self.assertEqual(\n            confirmed["summary"]["exactConfirmedSourceLabels"],\n            len(exact_items),\n        )\n        self.assertEqual(\n            confirmed["summary"]["semanticEquivalentConfirmedSourceLabels"],\n            len(equivalence_items),\n        )\n        self.assertEqual(\n            confirmed["summary"]["syntacticConfirmedSourceLabels"],\n            len(syntax_ids),\n        )\n        self.assertEqual(confirmed["summary"]["confirmedSourceLabels"], total)\n        self.assertEqual(\n            baseline["summary"]["needsSemanticConfirmationSourceLabels"]\n            - confirmed["summary"]["needsSemanticConfirmationSourceLabels"],\n            total,\n        )\n        self.assertEqual(\n            baseline["summary"]["semanticConcepts"]\n            - confirmed["summary"]["semanticConcepts"],\n            total,\n        )\n        self.assertEqual(\n            confirmed["summary"]["needsSemanticConfirmationSourceLabels"],\n            baseline["summary"]["needsSemanticConfirmationSourceLabels"] - total,\n        )\n'''
new = '''        confirmed = mod.compile_from_paths(paths)\n        total = len(confirmation_items) + len(syntax_ids)\n        standalone = mod._load_standalone_payload(\n            tools / "release_catalog_semantic_standalone_dispositions.v1.json"\n        )\n        standalone_count = len(standalone.get("items") or [])\n        review_total = total + standalone_count\n\n        self.assertEqual(\n            confirmed["summary"]["exactConfirmedSourceLabels"],\n            len(exact_items),\n        )\n        self.assertEqual(\n            confirmed["summary"]["semanticEquivalentConfirmedSourceLabels"],\n            len(equivalence_items),\n        )\n        self.assertEqual(\n            confirmed["summary"]["syntacticConfirmedSourceLabels"],\n            len(syntax_ids),\n        )\n        self.assertEqual(\n            confirmed["summary"]["standaloneConfirmedSourceLabels"],\n            standalone_count,\n        )\n        self.assertEqual(confirmed["summary"]["confirmedSourceLabels"], total)\n        self.assertEqual(\n            baseline["summary"]["needsSemanticConfirmationSourceLabels"]\n            - confirmed["summary"]["needsSemanticConfirmationSourceLabels"],\n            review_total,\n        )\n        self.assertEqual(\n            baseline["summary"]["semanticConcepts"]\n            - confirmed["summary"]["semanticConcepts"],\n            total,\n        )\n        self.assertEqual(\n            confirmed["summary"]["needsSemanticConfirmationSourceLabels"],\n            baseline["summary"]["needsSemanticConfirmationSourceLabels"] - review_total,\n        )\n'''
if text.count(old) != 1:
    raise SystemExit(f'standalone regression insertion point count={text.count(old)}')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
