#!/usr/bin/env python3
"""Offline-only review re-overlay for an already captured Cook4Me v60 artifact.

This tool exists specifically so a proven provider capture never needs to be
repeated merely because semantic/provider review evidence advanced afterwards.
It performs no provider or USDA/FDC calls and never mutates the input payload.

The captured v60 artifact already contains exact Phase-3 source evidence on each
source-local recipe line as ``semanticSourceName``.  Global source-local rows may
still contain the older unreviewed state, so they are removed only after proving
that every such identity is referenced by recipe-line evidence and that each
line deterministically reproduces its persisted ``local:<lang>:...`` identity.
The established v60 semantic compiler then rebuilds those globals, exact provider
canonical-English reviews are overlaid, and derived search/safety indexes are
regenerated by the existing v60 implementation.
"""
from __future__ import annotations

import argparse
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
for path in (ROOT, TOOLS):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import build_release_catalog_v60 as base  # noqa: E402
import build_release_catalog_v60_reviewed as reviewed  # noqa: E402
import compile_release_catalog_semantics_v60 as semantics  # noqa: E402
import provider_identity_v60  # noqa: E402
import release_catalog_phase3_identity_v60 as phase3_identity  # noqa: E402
import validate_release_catalog_v60 as validator  # noqa: E402

CAPTURE3_VERSION = "2026-09-11-v60-capture3"


def _text(value: Any) -> str:
    return " ".join(str(value or "").strip().split())


def _identity(row: dict[str, Any]) -> str:
    return _text(
        row.get("id")
        or row.get("ingredientId")
        or row.get("key")
        or row.get("foodKey")
    )


def _source_local(row: dict[str, Any], ident: str = "") -> bool:
    ident = ident or _identity(row)
    return bool(row.get("sourceLocalIdentity")) or ident.startswith("local:")


def _provider_global_ids(payload: dict[str, Any]) -> set[str]:
    ids: set[str] = set()
    for row in payload.get("ingredients") or []:
        if not isinstance(row, dict):
            continue
        ident = _identity(row)
        if not ident or _source_local(row, ident):
            continue
        if not provider_identity_v60.preserved_provider_identity(row, ident):
            raise RuntimeError(
                f"non-source-local global ingredient does not preserve provider identity: {ident}"
            )
        ids.add(ident)
    return ids


def _source_local_global_ids(payload: dict[str, Any]) -> set[str]:
    out: set[str] = set()
    for row in payload.get("ingredients") or []:
        if not isinstance(row, dict):
            continue
        ident = _identity(row)
        if ident and _source_local(row, ident):
            if not ident.startswith("local:"):
                raise RuntimeError(
                    f"source-local global row does not use local: identity: {ident}"
                )
            out.add(ident)
    return out


def _exact_source_local_recipe_ids(payload: dict[str, Any]) -> set[str]:
    """Prove every captured source-local line from exact retained source evidence."""
    out: set[str] = set()
    for group in payload.get("recipes") or []:
        if not isinstance(group, dict):
            continue
        for variant in group.get("variants") or []:
            if not isinstance(variant, dict):
                continue
            variant_id = _text(variant.get("variantId") or variant.get("searchVariantId"))
            for row in variant.get("ingredients") or []:
                if not isinstance(row, dict):
                    continue
                ident = _identity(row)
                if not ident.startswith("local:") and row.get("sourceLocalIdentity") is not True:
                    continue
                if not ident.startswith("local:"):
                    raise RuntimeError(
                        f"source-local recipe line in {variant_id or '?'} has invalid identity {ident!r}"
                    )
                source = phase3_identity.compact_semantic_source_name(row)
                language = _text(
                    row.get("originalLanguage") or row.get("language")
                ).lower()
                if not source or not language:
                    raise RuntimeError(
                        f"source-local recipe line {variant_id or '?'}:{ident} lacks exact Phase-3 source evidence"
                    )
                expected = semantics.source_local_ingredient_id(language, source)
                if expected != ident:
                    raise RuntimeError(
                        "captured source-local identity/source mismatch: "
                        f"{variant_id or '?'}:{ident} != {expected} for {language}/{source!r}"
                    )
                out.add(ident)
    return out


def apply_offline_review_overlay(
    payload: dict[str, Any],
    *,
    review_root: Path = TOOLS,
    semantic_payload: dict[str, Any] | None = None,
    expected_catalog_version: str | None = CAPTURE3_VERSION,
) -> dict[str, Any]:
    """Reapply current committed review evidence to one immutable capture."""
    if expected_catalog_version is not None:
        actual_version = _text(payload.get("catalogVersion"))
        if actual_version != expected_catalog_version:
            raise RuntimeError(
                f"catalogVersion mismatch: expected {expected_catalog_version!r}, got {actual_version!r}"
            )

    original_provider_ids = _provider_global_ids(payload)
    original_local_globals = _source_local_global_ids(payload)
    exact_recipe_local_ids = _exact_source_local_recipe_ids(payload)
    if original_local_globals != exact_recipe_local_ids:
        missing_from_recipes = sorted(original_local_globals - exact_recipe_local_ids)
        missing_from_globals = sorted(exact_recipe_local_ids - original_local_globals)
        raise RuntimeError(
            "captured source-local global/recipe identity sets differ: "
            f"globals_without_recipe={missing_from_recipes[:10]} "
            f"recipes_without_global={missing_from_globals[:10]}"
        )

    staged = deepcopy(payload)
    staged["ingredients"] = [
        deepcopy(row)
        for row in staged.get("ingredients") or []
        if isinstance(row, dict) and not _source_local(row)
    ]

    compiled = semantic_payload
    if compiled is None:
        paths = semantics._review_paths(review_root)
        if not paths:
            raise RuntimeError(f"no semantic review files in {review_root}")
        compiled = semantics.compile_from_paths(paths)

    result = base.enrich_payload(staged, compiled)
    rebuilt_local_ids = _source_local_global_ids(result)
    if rebuilt_local_ids != original_local_globals:
        raise RuntimeError(
            "semantic re-overlay changed the exact source-local identity set"
        )
    if _provider_global_ids(result) != original_provider_ids:
        raise RuntimeError("semantic re-overlay changed the exact provider identity set")

    source = result.get("source") if isinstance(result.get("source"), dict) else {}
    if source.get("semanticCoverageComplete") is not True:
        raise RuntimeError("semantic re-overlay did not reach complete semantic coverage")
    if int(source.get("unresolvedKeylessRecipeLineCount") or 0) != 0:
        raise RuntimeError("semantic re-overlay left unresolved keyless recipe lines")

    result = reviewed.apply_capture_canonical_reviews(
        result,
        review_root=review_root,
    )
    if _provider_global_ids(result) != original_provider_ids:
        raise RuntimeError("canonical review overlay changed the exact provider identity set")
    if _source_local_global_ids(result) != original_local_globals:
        raise RuntimeError("canonical review overlay changed the exact source-local identity set")

    source = result.get("source") if isinstance(result.get("source"), dict) else {}
    if int(source.get("unresolvedCanonicalIngredientNames") or 0) != 0:
        raise RuntimeError("canonical review overlay left unresolved ingredient names")
    if int(source.get("unresolvedCanonicalRecipeNames") or 0) != 0:
        raise RuntimeError("canonical review overlay left unresolved recipe names")

    source.update(
        {
            "offlineReviewReoverlayApplied": True,
            "offlineReviewReoverlayProviderCalls": False,
            "offlineReviewReoverlayNutritionCalls": False,
            "offlineReviewReoverlayInputMutated": False,
            "offlineReviewReoverlaySourceLocalGlobalsRebuilt": len(original_local_globals),
            "offlineReviewReoverlayProviderIdentityCount": len(original_provider_ids),
        }
    )
    result["complete"] = reviewed._capture_complete(result)
    return result


def _load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeError(f"{path}: expected JSON object")
    return value


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--review-root", default=str(TOOLS))
    parser.add_argument("--catalog-version", default=CAPTURE3_VERSION)
    args = parser.parse_args()

    source_path = Path(args.catalog).expanduser()
    output_path = Path(args.output).expanduser()
    review_root = Path(args.review_root).expanduser()
    payload = _load(source_path)
    before = deepcopy(payload)
    result = apply_offline_review_overlay(
        payload,
        review_root=review_root,
        expected_catalog_version=args.catalog_version,
    )
    if payload != before:
        raise RuntimeError("offline review re-overlay mutated its input payload")

    validation = validator.validate(
        result,
        require_complete=True,
        require_intelligence=False,
    )
    errors = validation.get("errors") or []
    if errors:
        raise RuntimeError(
            "offline reviewed artifact failed v60 validation: "
            + " | ".join(str(item) for item in errors[:20])
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    base._core._save_compact(output_path, result)
    source = result.get("source") if isinstance(result.get("source"), dict) else {}
    print(
        json.dumps(
            {
                "catalogVersion": result.get("catalogVersion"),
                "complete": result.get("complete") is True,
                "semanticCoverageComplete": source.get("semanticCoverageComplete") is True,
                "unresolvedKeylessRecipeLineCount": int(
                    source.get("unresolvedKeylessRecipeLineCount") or 0
                ),
                "unresolvedCanonicalIngredientNames": int(
                    source.get("unresolvedCanonicalIngredientNames") or 0
                ),
                "unresolvedCanonicalRecipeNames": int(
                    source.get("unresolvedCanonicalRecipeNames") or 0
                ),
                "sourceLocalGlobalsRebuilt": int(
                    source.get("offlineReviewReoverlaySourceLocalGlobalsRebuilt") or 0
                ),
                "providerIdentityCount": int(
                    source.get("offlineReviewReoverlayProviderIdentityCount") or 0
                ),
                "validationWarnings": validation.get("warnings") or [],
                "inputSha256": _sha256(source_path),
                "outputSha256": _sha256(output_path),
                "output": str(output_path),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
